//
//  LKCStyleKit.h
//  OctoberBaby
//
//  Created by thuai on 14-7-6.
//  Copyright (c) 2014 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
@class UIBezierPath;

@interface LKCStyleKit : NSObject

@property (nonatomic , strong) UIBezierPath* bezierPath;

// Colors
+ (UIColor*)naviTitleColor;
+ (UIColor*)inputBgColor;
+ (UIColor*)tabBarTitleColor;
+ (UIColor*)borderColor;
+ (UIColor*)tabbarTint;

// Drawing Methods
//  画手动胎动图标
+ (void)drawManual_fetalWithFrame: (CGRect)frame;

// 画自动胎动图标
+ (void)drawAuto_fetalWithFrame: (CGRect)frame;

//  画宫缩复位图标
+ (void)drawTocoResetWithFrame : (CGRect)frame;
@end
